version: '3.8'

services:
  triton-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # HTTP API
      - "8001:8001"  # gRPC API
      - "8002:8002"  # Metrics
    volumes:
      - ./model_repository_2:/model_repository
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    networks:
      - shared-network

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/v2/health/ready" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    shm_size: "3g"

#    stdin_open: true  # Interaktif terminal
#    tty: true         # Terminal open
#    command: /bin/bash

networks:
  shared-network:
    driver: bridge