name: "vit_preprocessing"
backend: "dali"
max_batch_size: 16
input [
  {
    name: "INPUT_0"
    data_type: TYPE_UINT8
    dims: [ -1 ]
  },
  {
    name: "INPUT_1"
    data_type: TYPE_INT32
    dims: [ 2 ]
  }
]
output [
  {
    name: "OUTPUT_0"
    data_type: TYPE_FP32
    dims: [ 3, 224, 224 ]
  }
]
instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]
